#%RAML 1.0 SecurityScheme
type: x-auth
describedBy:
  headers:
    username:
      type: string
      required: true
      minLength: 3
      maxLength: 10
      example: "surya"
    password:
      type: string
      required: true
      minLength: 3
      maxLength: 10
      example: "skjdfhg"
        
        
